---
- name: Install sudo and configure user on Debian localhost
  hosts: localhost
  become: true
  gather_facts: false

  vars:
    user_name: "dc"

  tasks:
    - name: Check if sudo is installed
      stat:
        path: /usr/bin/sudo
      register: sudo_check

    - name: Install sudo if not present
      command: apt-get install sudo -y
      when: not sudo_check.stat.exists

    - name: Disable su
      command: mv /bin/su /bin/su.disabled
      args:
        creates: /bin/su.disabled
      register: disable_su_result
      become: true

    - name: Add user to sudo group
      user:
        name: "{{ user_name }}"
        groups: sudo
        append: yes
      when: disable_su_result is success

    - name: Configure sudoers file
      lineinfile:
        path: /etc/sudoers
        line: "{{ user_name }} ALL=(ALL:ALL) ALL"
        validate: 'visudo -cf %s'
      when: disable_su_result is success

    - name: Notify user to log out and log back in
      debug:
        msg: "su has been disabled, sudo has been installed and configured for user '{{ user_name }}'. Please log out and log back in to apply the changes."
      when: disable_su_result is success
